//
//  DiseasePredictionRepository.swift
//  Robodoc
//
//  Created by IT Division on 09/06/21.
//

import Foundation

class DiseasePredictionRepository {
    let db: [(String, String)] = [
        ("Acute kidney injury", "Decreased amount and frequency of urine"),
        ("Acute kidney injury"," Swelling of the legs due to fluid buildup"),
        ("Acute kidney injury"," Body tired easily"),
        ("Acute kidney injury","Hard to breathe"),
        ("Acute kidney injury","Heart rhythm disturbances"),
        ("Acute kidney injury","Pain or a feeling of pressure in the chest"),
        ("Acute kidney injury","Bad breath"),
        ("Acute kidney injury","Decreased appetite"),
        ("Acute kidney injury","Nausea and vomiting"),
        ("Acute kidney injury","Fever"),
        ("Acute kidney injury","Pain in stomach and back"),
        ("Acute kidney injury","Pain or swelling in the joints"),
        ("Acute kidney injury","Tremor in hand"),
        ("Acute kidney injury","Seizure"),
        ("Acute kidney injury","Coma"),
        ("Heart Failure", "Easy bruising and bleeding"),
        ("Heart Failure", "Yellow skin and eyes"),
        ("Heart Failure", "Accumulation of fluid in the stomach"),
        ("Heart Failure", "Vomiting blood or bloody stools (black)"),
        ("Heart Failure", "Foggy consciousness and muddled speech"),
        ("Heart Failure", "Unconscious"),
        ("Stutter", "Have difficulty in speaking"),
        ("Stutter", "Repeating or prolonging the mention of a word"),
        ("Stutter", "Often take pauses in speaking"),
        ("Stutter", "Avoiding eye contact with the other person"),
        ("Stutter", "Trembling lips"),
        ("Stutter", "Excessive blinking of the eyes"),
        ("Stutter", "Tension in the face"),
        ("Stutter", "Frequent clenching of the hands"),
        ("Stutter", "Facial muscle twitching"),
        ("Gastritis", "Pain that feels hot and stinging in"),
        ("Gastritis", "The upper part of the stomach"),
        ("Gastritis", "Bloated"),
        ("Gastritis", "Hiccup"),
        ("Gastritis", "Nausea"),
        ("Gastritis", "Gag"),
        ("Gastritis", "Puke"),
        ("Gastritis", "Vomit"),
        ("Gastritis", "Loss of appetite"),
        ("Gastritis", "Quickly feel full when eating"),
        ("Gastritis", "Passing stools with black stools."),
        ("Gastritis", "Vomiting blood"),
        ("Indigestion", "Difficult to swallow"),
        ("Indigestion", "A burning sensation in the chest (heartburn)"),
        ("Indigestion", "Nausea"),
        ("Indigestion", "Gag"),
        ("Indigestion", "Puke"),
        ("Indigestion", "Vomit"),
        ("Indigestion", "Bloated"),
        ("Indigestion", "Gastric pains"),
        ("Indigestion", "Stomach ache"),
        ("Indigestion", "Diarrhea"),
        ("Indigestion", "Constipation"),
        ("Indigestion", "Vomiting blood or bloody stools"),
        ("Indigestion", "Weight gain or loss"),
        ("Hepatitis C", "Limp"),
        ("Hepatitis C", "Have no appetite"),
        ("Hepatitis C", "Jaundice"),
        ("Hypertension", "Nausea"),
        ("Hypertension", "Gag"),
        ("Hypertension", "Puke"),
        ("Hypertension", "Vomit"),
        ("Hypertension", "Headache"),
        ("Hypertension", "Nosebleed"),
        ("Hypertension", "Hard to breathe"),
        ("Hypertension", "Chest pain"),
        ("Hypertension", "Visual disturbance"),
        ("Hypertension", "Ears ringing"),
        ("Hypertension", "Heart rhythm disturbances"),
        ("Hypertension", "Blood in urine"),
        ("Hemophilia", "Bleeding in the nose (nosebleeds) that is difficult to stop"),
        ("Hemophilia", "Bleeding in wounds that are difficult to stop"),
        ("Hemophilia", "Bleeding in the gums"),
        ("Hemophilia", "Bleeding after circumcision (circumcision) that is difficult to stop"),
        ("Hemophilia", "Blood in the urine and feces (feces)"),
        ("Hemophilia", "Easy bruising"),
        ("Hemophilia", "Bleeding in the joints characterized by pain and swelling in the elbow and knee joints"),
        ("Impotence", "Difficulty getting an erection"),
        ("Impotence", "Difficulty maintaining an erection"),
        ("Impotence", "Decreased sexual desire."),
        ("Fungal Infection", "Red or purple spots on the skin"),
        ("Fungal Infection", "Skin rash appears"),
        ("Fungal Infection", "Cracked skin"),
        ("Fungal Infection", "Blisters or pus"),
        ("Fungal Infection", "Itchy rash"),
        ("Fungal Infection", "Pain in the infected area"),
        ("Fungal Infection", "Swelling in the infected area"),
        ("Fungal Infection", "Cough with blood or mucus"),
        ("Fungal Infection", "Hard to breathe"),
        ("Fungal Infection", "Fever"),
        ("Fungal Infection", "Blurred vision"),
        ("Fungal Infection", "Red eyes and sensitive to light"),
        ("Fungal Infection", "Excessive tears"),
        ("Fungal Infection", "Headache"),
        ("Fungal Infection", "Nasal congestion"),
        ("Fungal Infection", "Nausea and vomiting"),
        ("Insomnia", "Having trouble sleeping or waking up frequently at night"),
        ("Insomnia", "Waking up too early in the morning"),
        ("Insomnia", "Sleep that feels restless or insufficient, such as drowsiness or tiredness during the day"),
        ("Insomnia", "Easily angry and depressed"),
        ("Insomnia", "Difficulty focusing on activities"),
        ("Upper Respiratory Tract Infection", "Cough"),
        ("Upper Respiratory Tract Infection", "Sneeze"),
        ("Upper Respiratory Tract Infection", "Nasal congestion"),
        ("Upper Respiratory Tract Infection", "Cold"),
        ("Upper Respiratory Tract Infection", "Sore throat"),
        ("Upper Respiratory Tract Infection", "Headache"),
        ("Upper Respiratory Tract Infection", "Feeling unwell"),
        ("Upper Respiratory Tract Infection", "Muscle ache"),
        ("Upper Respiratory Tract Infection", "Cold"),
        ("Upper Respiratory Tract Infection", "Fever"),
        ("Nail fungus", "Nails thickened"),
        ("Nail fungus", "White spots appear on the nails"),
        ("Nail fungus", "Nails turn white, brownish yellow, or black"),
        ("Nail fungus", "Nails become rough and brittle"),
        ("Nail fungus", "The nail is separated from the skin of the finger where it attaches"),
        ("Nail fungus", "There is an unpleasant smell on the nails"),
        ("Acne", "The appearance of black or white spots (blackheads)"),
        ("Palpitations", "Body feels weak"),
        ("Palpitations", "Hard to breathe"),
        ("Palpitations", "Excessive sweating"),
        ("Palpitations", "Great dizziness"),
        ("Palpitations", "Fainted"),
        ("Palpitations", "The chest hurts and feels like it is being pressed"),
        ("Palpitations", "Pain in the arms, neck, jaw, and back"),
        ("Palpitations", "The resting pulse rate is still more than 100 beats per minute"),
        ("Cancer", "A lump appears"),
        ("Cancer", "Pain in one part of the body"),
        ("Cancer", "Pale, limp, and tired quickly"),
        ("Cancer", "Drastic weight loss"),
        ("Cancer", "Disturbances in defecation or defecation"),
        ("Cancer", "Chronic cough"),
        ("Cancer", "Recurring fever."),
        ("Cancer", "Bruising and bleeding spontaneously"),
        ("Dandruff", "Many and cause a very itchy scalp"),
        ("Dandruff", "Makes the scalp red and swollen"),
        ("Dandruff", "Did not improve in a month despite using anti-dandruff shampoo"),
        ("Dandruff", "Spread to other areas of the body, such as ears, eyebrows, nose, and sideburns"),
        ("Dandruff", "Causes hair loss"),
        ("Blackheads", "Small bumps that appear in the pores of the skin"),
        ("Blackheads", "Usually appears on facial skin"),
        ("Blackheads", "Does not cause pain"),
        ("Constipation", "Having to strain during bowel movements"),
        ("Constipation", "Feeling unfinished after a bowel movement"),
        ("Constipation", "Stool looks dry, hard, or lumpy"),
        ("Constipation", "It feels like something is stuck in the rectum or the very end of the large intestine"),
        ("Constipation", "Bloated"),
        ("Constipation", "Stomach ache"),
        ("Constipation", "Need help passing stool, such as using your hands to remove stool from the anus"),
        ("Leukemia", "Fever and chills"),
        ("Leukemia", "The body feels tired and fatigue does not go away even after resting"),
        ("Leukemia", "Drastic weight loss"),
        ("Leukemia", "Symptoms of anemia"),
        ("Leukemia", "Red spots on the skin"),
        ("Leukemia", "Nosebleed"),
        ("Leukemia", "Body bruises easily"),
        ("Leukemia", "Excessive sweating (especially at night)"),
        ("Leukemia", "Easy to get infected"),
        ("Leukemia", "A lump appears in the neck due to swollen lymph nodes"),
        ("Leukemia", "Stomach feels uncomfortable due to swollen liver and spleen"),
        ("Burns", "The skin becomes red and swollen"),
        ("Burns", "It hurts"),
        ("Burns", "The skin becomes dry after the burn heals"),
        ("Burns", "The skin is swollen and red, or white with red patches"),
        ("Burns", "There are blisters"),
        ("Burns", "Over time, the blisters rupture and thick, soft tissue, like a scab, forms around the wound"),
        ("Burns", "There is scarring in deep burns"),
        ("Burns", "Burnt skin is black, brown, or white"),
        ("Burns", "The skin becomes raised or feels rough and hard"),
        ("Burns", "No blisters"),
        ("Burns", "These burns damage nerves so that they can numb the skin"),
        ("Laryngitis", "Discomfort in the throat"),
        ("Laryngitis", "Dry throat"),
        ("Laryngitis", "Sore throat"),
        ("Laryngitis", "Cough"),
        ("Laryngitis", "Fever"),
        ("Laryngitis", "Voice becomes hoarse or even disappears"),
        ("Lupus", "Joint pain and stiffness"),
        ("Lupus", "Rash on the skin, often on the cheeks and nose"),
        ("Lupus", "Unexplained fatigue"),
        ("Lupus", "Skin is more sensitive to sunlight"),
        ("Lupus", "Weight loss"),
        ("Lupus", "Fever for no apparent reason"),
        ("Lupus", "Paleness of fingers or toes"),
        ("Lupus", "Sprue"),
        ("Malaria", "Fever"),
        ("Malaria", "Shivering"),
        ("Malaria", "Headache"),
        ("Malaria", "Sweat a lot"),
        ("Malaria", "Limp"),
        ("Malaria", "Sore"),
        ("Malaria", "Symptoms of anemia or lack of blood"),
        ("Malaria", "Nausea or vomiting"),
        ("Malaria", "Stomach pain"),
        ("Malaria", "Diarrhea and bloody stools"),
        ("Nausea", "Feeling like throwing up and discomfort in the stomach."),
        ("Migraine", "Mood swings"),
        ("Migraine", "Desire to eat certain foods"),
        ("Migraine", "Neck gets stiff"),
        ("Migraine", "Frequent yawning"),
        ("Migraine", "Constipation"),
        ("Migraine", "Often feel thirsty"),
        ("Migraine", "Frequent urination"),
        ("Migraine", "Experiencing verbal, sensory, and motor disturbances"),
        ("Migraine", "Visual disturbances, such as seeing flashes of light and blurred vision"),
        ("Migraine", "Headache on one side or sometimes on both sides of the head"),
        ("Migraine", "Head feels throbbing or tingling"),
        ("Migraine", "Blurred vision"),
        ("Migraine", "Dizziness"),
        ("Migraine", "Nausea and vomiting"),
        ("Migraine", "Sensitive to light, sound, smell and touch"),
        ("Migraine", "Mood swings"),
        ("Migraine", "Mild headache"),
        ("Migraine", "Fatigue"),
        ("Migraine", "Sensitive to light and sound"),
        ("Migraine", "Sweat"),
        ("Migraine", "Feeling very hot or very cold"),
        ("Migraine", "Stomach ache"),
        ("Migraine", "Diarrhea"),
        ("Migraine", "Difficulty concentrating"),
        ("Narcolepsy", "Hallucination"),
        ("Narcolepsy", "excessive sleepiness during the day"),
        ("Narcolepsy", "katapleksi"),
        ("Narcolepsy", "sleep paralysis"),
         ("Neurodermatitis","The feeling of itchiness that can occur continuously."),
         ("Chest Pain","Chest pain that gets worse when doing some activity"),
         ("Knee Pain","Knees feel stiff"),
        ("Knee Pain","knees looks red and swollen"),
        ("Knee Pain","knee feels weak and unstable"),
         ("Back Pain","Back feel stiff and swollen"),
         ("Neuroblastoma","Stomach ache"),
        ("Neuroblastoma","constipation"),
        ("Neuroblastoma","swelling stomache"),
        ("Neuroblastoma","sudden weight loss."),
         ("Anus Pain","Pain in the anus that appears suddenly"),
        ("Anus Pain","pain in the anus when defecating."),
         ("Neck Pain","Headache"),
        ("Neck Pain","hard to swallow"),
        ("Neck Pain","hard to move neck"),
         ("Muscle Pain (Myalgia)","Muscle cram"),
        ("Muscle Pain (Myalgia)","fever"),
         ("Wrist Pain","Fever"),
         ("Wrist Pain","soreness"),
         ("Wrist Pain","tingling"),
         ("Wrist Pain","numbness in the wrist"),
         ("Wrist Pain","warm feeling in the wrist."),
         ("Joint Pain","Joints feel warm and stiff, and reduced or limited joint movement."),
         ("Joint Pain","reduced or limited joint movement."),
         ("Obesity","Diabetes (Possible), and heart disease."),
         ("Orchitis","Fever"),
        ("Orchitis","nausea and vomiting"),
        ("Orchitis","swelling on one or both testicles."),
         ("Osteoporosis","Bones break easily even by a slight bump"),
        ("Osteoporosis","bending body posture."),
         ("Osteoarthritis","Joints swelling"),
         ("Osteoarthritis","appearance of lumps in the joints in the fingers."),
         ("Acute Pancreatitis","fever"),
         ("Acute Pancreatitis","diarrhea"),
         ("Acute Pancreatitis","nausea and vomiting"),
         ("Acute Pancreatitis","stomache swelling"),
         ("Acute Pancreatitis","indigestion."),
         ("Tinea Versicolor","The appearance of white marks"),
         ("Tinea Versicolor","the skin feels dry or scaly and itchy."),
         ("Parestesia","numbness."),
         ("Broken Wrist","numbness"),
        ("Broken Wrist","hard to move fingers"),
         ("Broken Bone","Bruise and swelling in the injured area"),
         ("Broken Bone","Pain"),
         ("Broken Bone","numbness."),
         ("Pneumonia","Coughing"),
         ("Pneumonia","fever"),
         ("Pneumonia","fatigue"),
         ("Pneumonia","hard to breathe"),
         ("Presbyopia","Can not see things far away."),
         ("Heart Disease","uncomfortable feeling in the chest area"),
         ("Heart Disease","headache"),
         ("Heart Disease","snoring"),
         ("Heart Disease","easily fatigue."),
         ("Polio","Paralyzed"),
        ("Polio","fever"),
        ("Polio","headache"),
        ("Polio","vomiting."),
         ("Polycystic Kidney Disease","stomach ache"),
         ("Polycystic Kidney Disease","hematuria"),
         ("Polycystic Kidney Disease","frequent urination."),
         ("PTSD","Negative thought and feelings"),
         ("PTSD","changes in behavior and emotions."),
         ("Headache","the surroundings feel like spinning or feeling about to pass out."),
         ("Rabies","Fever"),
        ("Rabies","headache"),
        ("Rabies","muscle weakness"),
        ("Rabies","tingling."),
         ("Rickets","Pain in the spine"),
         ("Rickets","bones break easily."),
         ("Rheumatoid","Joints swelling"),
         ("Nightsightedness","Hard to see in the dark."),
         ("Rhabdomyolysis","Urine is reddish or brown in color"),
         ("Rhabdomyolysis","hard to move hands."),
         ("Rubella","Fever"),
         ("Rubella","headache"),
         ("Rubella","no appetite."),
         ("Tooth Pain","hard to swallow"),
         ("Tooth Pain","hard to breathe"),
         ("Tooth Pain","swollen gums"),
        ("Tooth Pain","Difficult and painful when opening the mouth"),
         ("SARS","fever"),
         ("SARS","coughing"),
         ("SARS","hard to breathe"),
         ("SARS","headache"),
         ("SARS","diarrhea"),
         ("SARS","nausea"),
         ("SARS","vomitting"),
         ("Syphilis","The appearance of a rash on the body"),
         ("Scoliosis","One shoulder is higher"),
         ("Scoliosis","uneven waist height"),
         ("Scoliosis","One of the shoulder blades looks more prominent"),
         ("Stress","Headache"),
         ("Stress","Migrain"),
         ("Stress","Frustation"),
         ("Stress","Uneasiness"),
         ("Stress","pessimistic"),
         ("Stroke","Hard to talk"),
         ("Stroke","on or both arms feel weak to the point where you can't move it"),
         ("Tuberculosis","fever"),
         ("Tuberculosis","fatigue"),
         ("Tuberculosis","chest pain"),
         ("Tuberculosis","no appetite"),
         ("Tetanus","fever"),
         ("Tetanus","headache"),
         ("Tetanus","excessive sweating"),
         ("Thalassemia","easily fatigue"),
         ("Typhus","fever"),
         ("Typhus","headache"),
         ("Typhus","muscle pain"),
         ("Typhus","stomache ache"),
         ("Brain Tumor","headache"),
         ("Brain Tumor","nervous breakdown"),
         ("Brain Tumor","seizure"),
         ("Thrombocytopenia","nosebleed"),
         ("Thrombocytopenia","bleeding gums"),
         ("Thrombocytopenia","hematuria"),
         ("Thrombocytopenia","bloody or black colored feces"),
        ("Urethritis", "Blood in urine"),
        ("Urethritis", "Burning sensation when urinating"),
        ("Urethritis", "Swollen lymph node around the crotch area"),
        ("Urethritis", "Pain during sexual intercourse"),
        ("Uveitis", "Red eyes"),
        ("Uveitis", "Pain on the eyes"),
        ("Uveitis", "Blurry vision"),
        ("Uveitis", "Seeing black spots"),
        ("Duodenal Ulcer", "Bloated belly"),
        ("Duodenal Ulcer", "Limp"),
        ("Duodenal Ulcer", "Nausea"),
        ("Duodenal Ulcer", "Lower appetite"),
        ("Duodenal Ulcer", "Heartburn"),
        ("Corneal Ulcer", "Watery eyes"),
        ("Corneal Ulcer", "White speck on cornea"),
        ("Corneal Ulcer", "Blurry vision"),
        ("Corneal Ulcer", "Sensitivity to light"),
        ("Vaginitis", "Itch around the vagina"),
        ("Vaginitis", "Redness and pain around the vagina"),
        ("Vaginitis", "Pain when urinating"),
        ("Vaginitis", "Pain during sexual intercourse"),
        ("Varicose veins", "Heavy feeling in the legs"),
        ("Varicose veins", "Skin discoloration around a varicose vein"),
        ("Varicose veins", "Itch around veins"),
        ("Varicose veins", "Pain after sitting or standing for a while"),
        ("Vasculitis", "Soreness around the body"),
        ("Vasculitis", "Sweating at night"),
        ("Vasculitis", "Fever"),
        ("Vasculitis", "Rash"),
        ("Ventricular fibrillation", "Loss of conciousness"),
        ("Ventricular fibrillation", "Chest pain"),
        ("Ventricular fibrillation", "Very fast heartbeat"),
        ("Ventricular fibrillation", "Nausea"),
        ("Vertigo", "Nausea"),
        ("Vertigo", "Loss of hearing"),
        ("Vertigo", "Sweating"),
        ("Vertigo", "Blurry vision"),
        ("Vertigo", "Abnormal eye movement"),
        ("Hemorrhoid", "Bump outside the anus"),
        ("Hemorrhoid", "Itch around the anus"),
        ("Hemorrhoid", "Bleeding after defecation"),
        ("Hemorrhoid", "Fluid discharge after defecation"),
        ("William's Syndrome", "Wide forehead"),
        ("William's Syndrome", "Asymmetrical eyes"),
        ("William's Syndrome", "High blood pressure"),
        ("William's Syndrome", "Short stature"),
        ("William's Syndrome", "Learning disorders"),
        ("William's Syndrome", "ADHD"),
        ("William's Syndrome", "Diabetes"),
        ("Wilson's Disease", "Muscle pains"),
        ("Wilson's Disease", "Lower speech, sight, and memory capabilities"),
        ("Wilson's Disease", "Insomnia"),
        ("Wilson's Disease", "Nausea"),
        ("Wilson's Disease", "Yellow skin"),
        ("Wilson's Disease", "Bloated belly"),
        ("Xanthelasma", "Yellow plaque around the eyes"),
        ("Xerophthalmia", "Itch around the eyes"),
        ("Xerophthalmia", "Burning sensation around the eyes"),
        ("Xerophthalmia", "Blurry vision"),
        ("Xerophthalmia", "Sensitivity to light"),
        ("Xerophthalmia", "Night blindness"),
        ("Xerosis", "Dry and rough skin on arms and legs"),
        ("Xerosis", "Pale skin"),
        ("Xerosis", "Redness from irritation"),
        ("Xerosis", "Rash"),
        ("Allergy", "Sneezing"),
        ("Allergy", "Itchy"),
        ("Allergy", "Runny"),
        ("Allergy", "Stuffy Nose"),
        ("Allergy", "Red Skin"),
        ("Allergy", "Dry Skin"),
        ("Allergy", "Cracked Skin"),
        ("Allergy", "Red Eyes"),
        ("Allergy", "Watery Eyes"),
        ("Allergy", "Cough"),
        ("Allergy", "Vomit"),
        ("Allergy", "Diarrhea"),
        ("Allergy", "Wheezing"),
        ("Allergy", "Blown"),
        ("Amnesia", "Hard Remember"),
        ("Amnesia", "Loss Memory"),
        ("Anemia", "Weakness"),
        ("Anemia", "Tired"),
        ("Anemia", "Headache"),
        ("Anemia", "Dizzy"),
        ("Anemia", "Sleepy"),
        ("Anemia", "Blown"),
        ("Anemia", "Irregular heartbeat"),
        ("Anemia", "Chest Pain"),
        ("Asthma", "Blown"),
        ("Asthma", "Cough"),
        ("Asthma", "Blue Lip"),
        ("Asthma", "Headache"),
        ("Asthma", "Tired"),
        ("Asthma", "Sleepy"),
        ("Asthma", "Hard Breath"),
        ("Asthma", "Chest Pain"),
        ("Cough", "Cough"),
        ("Cough", "Fever"),
        ("Cough", "Tired"),
        ("Cough", "Hard Swallow"),
        ("Cough", "Blown"),
        ("Cough", "Cold"),
        ("Cold", "Cold"),
        ("Cold", "Nasal Congestion"),
        ("Cold", "Crack Voice"),
        ("Cold", "Headache"),
        ("Cold", "Fever"),
        ("Cold", "Hard Sniff"),
        ("Cold", "Watery Eye"),
        ("Cold", "Reduced Smell"),
        ("Cold", "Reduced Tasting"),
        ("Bald", "No Hair"),
        ("Bald", "Broken Hair"),
        ("Bald", "Unhealthy Hair"),
        ("Bald", "Reduced Hair Produce"),
        ("Boil", "Boil"),
        ("Boil", "Red Bump"),
        ("Boil", "Pain Red Bump"),
        ("Stye", "Red Eye Bump"),
        ("Stye", "Red Eye"),
        ("Stye", "Red Eyelid"),
        ("Stye", "Swollen Eyelid"),
        ("Stye", "Watery Eye"),
        ("Gallstone", "Nausea"),
        ("Gallstone", "Puke"),
        ("Gallstone", "Gag"),
        ("Gallstone", "Vomit"),
        ("Gallstone", "Puke"),
        ("Gallstone", "Gastric Pain"),
        ("Gallstone", "Ulcer"),
        ("Gallstone", "Diarrhea"),
        ("Gallstone", "Bloated"),
        ("KidneyStone", "Back Pain"),
        ("KidneyStone", "Frequent Urination"),
        ("KidneyStone", "Disuria"),
        ("KidneyStone", "Urination Pain"),
        ("KidneyStone", "Red Urine"),
        ("KidneyStone", "Brown Urine"),
        ("KidneyStone", "Nausea"),
        ("KidneyStone", "Puke"),
        ("KidneyStone", "Gag"),
        ("KidneyStone", "Vomit"),
        ("KidneyStone", "Throw Up"),
        ("KidneyStone", "Fever"),
        ("Covid", "Fever"),
        ("Covid", "Cough"),
        ("Covid", "Blown"),
        ("Covid", "Hard Breath"),
        ("Covid", "Tired"),
        ("Covid", "Chest Pain"),
        ("Covid", "Sore Throat"),
        ("Covid", "Reduced Smell"),
        ("Covid", "Reduced Taste"),
        ("Covid", "Diarrhea"),
        ("Covid", "Nausea"),
        ("Covid", "Nasal Congestion"),
        ("Covid", "Headache"),
        ("Covid", "High Temperature"),
        ("Corona", "Fever"),
        ("Corona", "Cough"),
        ("Corona", "Blown"),
        ("Corona", "Hard Breath"),
        ("Corona", "Tired"),
        ("Corona", "Chest Pain"),
        ("Corona", "Sore Throat"),
        ("Corona", "Reduced Smell"),
        ("Corona", "Reduced Taste"),
        ("Corona", "Diarrhea"),
        ("Corona", "Nausea"),
        ("Corona", "Nasal Congestion"),
        ("Corona", "Headache"),
        ("Corona", "High Temperature"),
        ("Measle", "Sore"),
        ("Measle", "Fever"),
        ("Measle", "Tired"),
        ("Measle", "Weak"),
        ("Measle", "Diarrhea"),
        ("Measle", "Nasal Congestion"),
        ("Measle", "Red Spot"),
        ("Measle", "White Spot"),
        ("Measle", "Puke"),
        ("Measle", "Red Eye"),
        ("Measle", "Light Sensitive"),
        ("Hiccup", "Hiccup"),
        ("Dehydration", "Thirsty"),
        ("Dehydration", "Darker Urine"),
        ("Dehydration", "Low Urination"),
        ("Dehydration", "Dry Mouth"),
        ("Dehydration", "Headache"),
        ("Dehydration", "Unfocus"),
        ("Dehydration", "Tired"),
        ("Dehydration", "Sleepy"),
        ("Dengue Fever", "High Temperature"),
        ("Dengue Fever", "Headache"),
        ("Dengue Fever", "Sore"),
        ("Dengue Fever", "Nausea"),
        ("Dengue Fever", "Puke"),
        ("Dengue Fever", "Gag"),
        ("Dengue Fever", "Vomit"),
        ("Dengue Fever", "Swollen Lymph Gland"),
        ("Dengue Fever", "Red Spot"),
        ("Dengue Fever", "Low Platelets"),
        ("Dengue Fever", "Low Trombochyte"),
        ("Fever", "Headache"),
        ("Fever", "Fever"),
        ("Fever", "Sweating"),
        ("Fever", "Weak"),
        ("Fever", "Shivering"),
        ("Fever", "Sore"),
        ("Fever", "Irregular Heartbeat"),
        ("Fever", "Nasal Congestion"),
        ("Fever", "Cold"),
        ("Fever", "Dehydration"),
        ("Fever", "Diarrhea"),
        ("Fever", "Cough"),
        ("Fever", "Red Skin"),
        ("Fever", "High Temperature"),
        ("Diabetes", "Thirsty"),
        ("Diabetes", "Frequent urination"),
        ("Diabetes", "Loss Weight"),
        ("Diabetes", "Hungry"),
        ("Diabetes", "Weak"),
        ("Diabetes", "Blurred Vision"),
        ("Diabetes", "Infection"),
        ("Diarrhea", "Fever"),
        ("Diarrhea", "Loss Weight"),
        ("Diarrhea", "Headache"),
        ("Diarrhea", "Thirsty"),
        ("Diarrhea", "Watery Stool"),
        ("Diarrhea", "Heartburn"),
        ("Diarrhea", "Nausea"),
        ("Diarrhea", "Puke"),
        ("Diarrhea", "Gag"),
        ("Diarrhea", "Vomit"),
        ("Epilepsy", "Seizure"),
        ("Epilepsy", "Headache"),
        ("Epilepsy", "Dizzy"),
        ("Epilepsy", "Tingling"),
        ("Epilepsy", "Reduced Smelling"),
        ("Epilepsy", "Reduced Breath"),
        ("Edema", "Swolen"),
        ("Edema", "Blown"),
        ("Edema", "Big Stomach"),
        ("Edema", "Hard Walk"),
        ("Ebola", "Red Eye"),
        ("Ebola", "Sore Throat"),
        ("Ebola", "Chest Pain"),
        ("Ebola", "Gastric Pain"),
        ("Ebola", "Diarrhea"),
        ("Ebola", "Nausea"),
        ("Ebola", "Puke"),
        ("Ebola", "Gag"),
        ("Ebola", "Vomit"),
        ("Ebola", "Throw Up"),
        ("Ebola", "Rash Skin"),
        ("Flu", "Fever"),
        ("Flu", "Cold"),
        ("Flu", "Nasal Congestion"),
        ("Flu", "Coughing"),
        ("Flu", "Sneezing"),
        ("Flu", "Sore Throat"),
        ("Flu", "Headache"),
        ("Flu", "Nausea"),
        ("Flu", "Gag"),
        ("Flu", "Throw Up"),
        ("Flu", "Vomit"),
        ("Flu", "Puke"),
        ("Flu", "Shivering"),
        ("Phobia", "Irregular Heartveat"),
        ("Phobia", "Confused"),
        ("Phobia", "Dizzy"),
        ("Phobia", "Chest Pain"),
        ("Phobia", "Dry Mouth"),
        ("Phobia", "Scared"),
        ("Phobia", "Frequent Urination"),
        ("Phobia", "Nervous"),
        ("Phobia", "Ringing Ears"),
        ("Pharyngitis", "Pain Swallow"),
        ("Pharyngitis", "Pain"),
        ("Pharyngitis", "Sore Throat"),
        ("Pharyngitis", "Fever"),
        ("Pharyngitis", "Nausea"),
        ("Pharyngitis", "Swollen Throat"),
        ("Pharyngitis", "Sore"),
        ("Pharyngitis", "Puke"),
        ("Pharyngitis", "Gag"),
        ("Pharyngitis", "Vomit"),
    ]
}
