# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'Robodoc' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for Robodoc
  pod 'IQKeyboardManagerSwift'
  pod 'RxSwift'
  pod 'RxCocoa'

  target 'RobodocTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'RobodocUITests' do
    # Pods for testing
  end

end
